# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
    paths-ignore:   # 下列文件的变更不触发部署，可以自行添加
      - README.md
      - ".github/**"
      - "src/README.md"
      - .gitignore
  pull_request:
    branches: [ "main" ]
    paths-ignore:   # 下列文件的变更不触发部署，可以自行添加
      - README.md
      - ".github/**"
      - .gitignore
      - "src/README.md"

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: execute python
      run: |
        python gen.py

    - name: Upload Pages artifact
      uses: actions/upload-pages-artifact@v2
      with:
          path: ./out
  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2  
        
    

